### ISSUE TITLE
Test server web interface

### ISSUE THREAD

**Issue by TGlas** [openml/OpenML#269]
It is possible to access the test server through the web interface at http://test.openml.org. However, for each and every link it keeps redirecting me to the "production" server http://www.openml.org. This way I don't manage to login on the test server. In particular I would like to make the read-only api_key of the Shark library demo account writable, but only on the test server. This is needed for unit testing.

**Comment by joaquinvanschoren** [comment]
Thanks. This was fixed a while ago :).

**Comment by TGlas** [comment]
This is still not working. In my browser I open http://test.openml.org/, I click "sign in", I enter the credentials of the shark test account, and voila, after submitting the login form I am back on www.openml.org. Going back to the test domain I am not logged in. This way I cannot make the key writable only on the test server.

**Comment by joaquinvanschoren** [comment]
Darn, it was fixed but then I reconfigured the web server. Fixed now!

[image: pasted1]

**Comment by TGlas** [comment]
> Darn, it was fixed but then I reconfigured the web server. Fixed now!

Thanks, it work. The actual URL of the test server seems to be 
http://capa.win.tue.nl, is it safe to hard-code this address into my 
unit test?
