### ISSUE TITLE
tags are not properly

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#319]
If we use tag filter: http://test.openml.org/api/v1/json/run/list/tag/myspecialtag/limit/2
The result does not contain this tag:

```
{"runs":{"run":[
    {"run_id":540249,
   "task_id":57,
   "setup_id":5391,
   "flow_id":5176,
   "uploader":348,
   "error_message":""
	   }
  ,  {"run_id":540306,
   "task_id":57,
   "setup_id":5391,
   "flow_id":5176,
   "uploader":348,
   "error_message":""
	 	 ,"tags": [
		 		 "curves"
	 ,		 "weka"
	 ,		 "weka_3.7.12-SNAPSHOT"
	 	 ]
 	   }
    ]}
}
```

**Comment by jakobbossek** [comment]
Please fix this soon. This is high priority!

**Comment by joaquinvanschoren** [comment]
Fixed

**Comment by jakobbossek** [comment]
There is still a problem. The JSON returned is invalid. Look at the runs with the *myspecialtag* tag. There are no values assigned to, e.g., run_id. Moreover, why do we get 4 runs? Only 2 of them are tagged with *myspecialtag*.

**Comment by mfeurer** [comment]
Thansk @jakobbossek for pointing this out, I did not see this.

**Comment by joaquinvanschoren** [comment]
Sorry, missed this. Fixed now. Please check.

**Comment by jakobbossek** [comment]
Thanks.
