### ISSUE TITLE
list/run returns invalid json?

### ISSUE THREAD

**Issue by giuseppec** [openml/OpenML#430]
This API call: https://www.openml.org/api/v1/json/run/list/task/31/limit/506
gives me an invalid json file (i.e. the error_message field of run.id 506400 looks strange according to https://jsonlint.com/ ). It seems that the error message field contains newline escape characters `\n` which are causing trouble in the JSON API, right?

Bugreport from https://github.com/openml/openml-r/issues/370

**Comment by joaquinvanschoren** [comment]
OK. @janvanrijn I think we can simply remove all such control characters in the JSON output, right?
If you agree, I'll fix that in the JSON template.

**Comment by joaquinvanschoren** [comment]
Fixed a while ago. Can I close this?

**Comment by giuseppec** [comment]
This still does not work. If I copy and paste the resulting JSON from https://www.openml.org/api/v1/json/run/list/task/31/limit/1/offset/505 to https://jsonlint.com/, I get

```
Error: Parse error on line 10:
...			"error_message": "Error in training t
-----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
```

**Comment by joaquinvanschoren** [comment]
This has been fixed. Can you check and close?

**Comment by giuseppec** [comment]
Solved, thx.
