### ISSUE TITLE
make data sets with parsing errors inactive

### ISSUE THREAD

**Issue by amueller** [openml/OpenML#475]
I find many data sets that have parsing errors, like this:
https://www.openml.org/d/1167

I think if the server couldn't read the data set, it should not be active.
That should be a simple SQL query to fix for existing data sets, and for new data sets I think they should not be labeled active if they couldn't be parsed by the server.

**Comment by amueller** [comment]
Related to #439.

**Comment by amueller** [comment]
Btw, one if the reasons why I insist on removing these faulty datasets is that I want to find out what kinds of errors there are. If we eliminate this source, we can find the others.

**Comment by joaquinvanschoren** [comment]
Hmm, 1167 is actually fine? Could also parse it with Python. Maybe something I fixed earlier.
I'll look at #439 now.

**Comment by amueller** [comment]
1597 and 1092 still have issues. Are those new issues? These two don't seem to be listed in #439.
I feel like it should be easy to alert on all server parsing errors. Is that not the case?
