### ISSUE TITLE
Broken links on website

### ISSUE THREAD

**Issue by Huii** [openml/OpenML#986]
You are really doing a great job with this project. Thank you very much for your efforts! However, I have to admit that the website looks a bit orphaned at first sight. One reason for that is that some links do not work:

If I want to upload data, for example, I have to " confirm that [I] have read and agreed to the OpenML Honor Code and Terms of Use." However, the corresponding link to those terms is broken: https://www.openml.org/guide/terms

Another problem is [this site](https://github.com/openml/OpenML/wiki/Data-Formats). It mentions the ARFF definition but only leads to: https://weka.wikispaces.com/ARFF. Unfortunately, Wikispace doesn't really work anymore.

**Comment by joaquinvanschoren** [comment]
Hi Huii, 

You are right. We are working on a completely new frontend and restructuring quite a few things, but it's taking a bit longer than anticipated. Stay tuned :).

I fixed the link to the terms and conditions (it actually was fixed in an earlier PR, I just had to pull the latest changes).

I'm not sure how you ended up on the wiki, but here is the new documentation:
https://docs.openml.org/Data-Formats/
To be sure, I fixed the link in the Wiki as well.

If you see other things that should be urgently fixed, let me know.

**Comment by Huii** [comment]
Thanks a lot for your reply, @joaquinvanschoren. Unfortunately, the terms and conditions are still broken for me if I want to add a new dataset. I clicked on the link in here:
"By submitting, you allow OpenML to index the data and link it to uploaded results. All rights remain with the original author(s) of the data. You confirm that you have read and agreed to the OpenML Honor Code and Terms of Use."

The wiki link is fixed. Thanks a lot. :)

**Comment by joaquinvanschoren** [comment]
Thanks. I created a PR here: https://github.com/openml/OpenML/pull/988
Once it's reviewed we can pull in on the production server.
